name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update && \
          sudo apt-get install -y docker-compose

      # Run Tests
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      # Run Linting
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
