name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Docker Compose explicitly
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Verify Docker Compose installation
      - name: Verify Docker Compose
        run: docker-compose --version

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Run Tests
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && 
                                                python manage.py test"

      # Lint
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
